#!/bin/bash
set -e
# set -x

if [ -z "$1" ] ; then
    $0 native-native-musl
    $0 native-native-gnu
    exit 0
fi

pkgname=libunistring
pkgver=1.1

cd "$(dirname "$0")"
TARGET=$1
ARCHDIR=$(echo $TARGET | cut -d - -f3)
DESTDIR="$(pwd)/$ARCHDIR"
BUILD="$DESTDIR/build-$TARGET"

export CC="zig cc --target=$TARGET"
export CXX="zig c++ --target=$TARGET"

rm -rf $DESTDIR/include $DESTDIR/lib $DESTDIR/config.h "$BUILD"
mkdir -p "$BUILD"
cd "$BUILD"

if ! [ -d ${pkgname}-${pkgver} ]; then
    curl -L https://ftp.gnu.org/gnu/$pkgname/${pkgname}-${pkgver}.tar.xz | tar -xJ
fi
cd ${pkgname}-${pkgver}

if ! [ -e config.log ] ; then
    ./configure --prefix="$DESTDIR"
fi
make -j "$(nproc)"
make install

echo 'pub const source_files = [_][]const u8{' > "$DESTDIR/libunistring.sources.zig"

find lib -name '*.o' | grep -v '/\.libs/' | sort -u | while read -r fn; do
    SRCDIR="$(dirname "$fn")"
    OFN="$(basename -s .o "$fn")"
    SRCFN=${OFN#libunistring_la-}
    SRC=$SRCDIR/$SRCFN.c
    if ! [ -e "$SRCDIR/$SRCFN.c" ] ; then
        echo " MISSING"
        exit 1
    fi

    cp -v --parents "$SRC" "$DESTDIR"
    echo "    \"$ARCHDIR/$SRC\"," >> "$DESTDIR/libunistring.sources.zig"
done
echo '};' >> "$DESTDIR/libunistring.sources.zig"

echo "pub const include_path = \"$ARCHDIR/include\";" >> "$DESTDIR/libunistring.sources.zig"
echo "pub const lib_include_path = \"$ARCHDIR/lib\";" >> "$DESTDIR/libunistring.sources.zig"
echo "pub const base_include_path = \"$ARCHDIR\";" >> "$DESTDIR/libunistring.sources.zig"

grep -IRn '#include.*\.c"' lib | cut -d ' ' -f2 | xargs -I{} echo lib/{} | sort -u | while read -r fn; do
    cp -v --parents "$fn" "$DESTDIR"
done

find lib -name '*.h' | while read -r fn; do
    cp -v --parents "$fn" "$DESTDIR"
done

cp -v config.h "$DESTDIR"

cd "$DESTDIR"
rm -rv lib/libunistring.*
rm -r share
rm -r "$BUILD"
sed -i "s|${DESTDIR}|libunistring-zig/musl|g" config.h
